services:
  get_iplayer:
    image: ghcr.io/sproglet/get_iplayer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 1000 # id -u
        PGID: 100  # id -g
    volumes:
      - /destination/on/host:/output
    ports:
      - "1935:1935"
